# Generated by Django 4.1.5 on 2023-01-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Title')),
                ('description', models.TextField()),
                ('state', models.BooleanField(default=False)),
                ('imageEvent', models.ImageField(blank=True, upload_to='images/')),
                ('nbParticipants', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Music', 'Music'), ('sport', 'Sport'), ('Cinema', 'Cinema')], max_length=10)),
                ('dateEvent', models.DateField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
